namespace DebateScoringEngine.Core.Scoring;

/// <summary>
/// The complete output of the scoring engine for one debate.
/// Contains the winner, full breakdown, and a human-readable explanation.
///
/// Two views of the same data:
///   Summary — StockIssueSummaries (one row per issue, default UI display)
///   Detail  — ArgumentDetails (one row per argument, drill-down UI display)
/// </summary>
public class ScoringResult
{
    // ── Winner ────────────────────────────────────────────────────────────────

    /// <summary>"AFF" or "NEG"</summary>
    public required string Winner { get; init; }

    /// <summary>One-sentence plain-English explanation of why this side won.</summary>
    public required string WinnerExplanation { get; init; }

    /// <summary>True if the round was decided by a hard gate issue before weighted scoring ran.</summary>
    public bool DecidedByHardGate { get; init; }

    /// <summary>The issue that triggered the hard gate, if applicable.</summary>
    public string? HardGateIssue { get; init; }

    // ── Scores ────────────────────────────────────────────────────────────────

    public double AffTotalScore { get; init; }
    public double NegTotalScore { get; init; }

    // ── Breakdowns ────────────────────────────────────────────────────────────

    /// <summary>One result per scoring rule — shows contribution of each rule.</summary>
    public required List<RuleResult> RuleResults { get; init; }

    /// <summary>
    /// Stock issue summaries — rolled up from all rules, weighted by config.
    /// This is the default display in the Summary tab.
    /// </summary>
    public required List<StockIssueSummary> StockIssueSummaries { get; init; }

    /// <summary>
    /// Per-argument score details across all rules — flattened for the Detail tab.
    /// </summary>
    public required List<ArgumentScoreDetail> ArgumentDetails { get; init; }

    /// <summary>
    /// Per-speaker score summaries — aggregated from all rules.
    /// Drives the Speaker tab in the UI.
    /// </summary>
    public required List<SpeakerScoreSummary> SpeakerScoreSummaries { get; init; }

    // ── Explanation ───────────────────────────────────────────────────────────

    /// <summary>
    /// Full human-readable explanation of the round result.
    /// Generated by ExplanationGenerator from the structured data above.
    /// </summary>
    public required string Explanation { get; init; }
}
